# Generated by Django 3.0.5 on 2021-03-30 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, 'Не меньше 0')]),
        ),
    ]
