# Generated by Django 3.0.5 on 2021-03-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210330_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='rating',
            new_name='rank',
        ),
    ]
