# Generated by Django 3.0.5 on 2021-03-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210328_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.AddField(
            model_name='title',
            name='rank',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
