# Generated by Django 3.0.5 on 2021-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210328_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rank',
        ),
        migrations.AddField(
            model_name='review',
            name='rank',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
